# Generated by Django 3.2.6 on 2023-04-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus_withdrawal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.DeleteModel(
            name='variables',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.DeleteModel(
            name='bonus_withdrawal',
        ),
        migrations.DeleteModel(
            name='deposit',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='withdrawal',
        ),
    ]
